### ISSUE TITLE
Release v1.0 checklist

### ISSUE THREAD

**Issue by slindberg** [lytics/ember-data-model-fragments#110]
Possibly v1.13?

- [x] Ember Data v1.13.x compatibility #99 
- [x] Stop using Ember's prototype extensions #104 
- [x] Allow for custom deserializing in transform #95 
- [x] Change default value of `DS.hasManyFragments` to be empty array #36, #40
- [x] Add ability to pass normalized JSON to `createFragment`, fragment attributes #10, #105
- [x] Support nested fragments when copying #98
- [x] Reset fragment owners when removed from a record #133
- [x] Use `DS.JSONSerializer` as default fragment serializer #135
- [x] Fix deprecation warnings (`Ember.create`, etc.)
- [x] Export `MF` global and create cli shim
- [x] Deprecate `DS.hasOneFragment` in favor of `MF.fragment`, `DS.hasManyFragments` for `MF.fragmentArray` & `MF.array` #11, #13 
- [ ] ~~Investigate record relationships #18~~

**Comment by knownasilya** [comment]
What's the status on this?

**Comment by karellm** [comment]
@slindberg Could you tell us what is going on? I think this is the only library in our project preventing us to move forward to `1.13` and `2.0`. Thanks!

**Comment by slindberg** [comment]
I decided to make this list the target for a 1.0 release, and added ED 1.13 compatibility in v0.4.0

**Comment by jackweinbender** [comment]
Is there any plan to make this work with the JSONAPI Serializer? It occurred to me that the JSONAPI spec supports  "any valid JSON value" for its attributes property. Assuming the ED team isn't planning on making this part of the Serializer, it seems like a good gap for EDMF to fill.

http://jsonapi.org/format/#document-resource-object-attributes

**Comment by jackweinbender** [comment]
Is there any plan to allow use with JSONAPI Serializer? I was noticing that [the JSONAPI spec states][1] that "Complex data structures involving JSON objects and arrays are allowed as attribute values," Which—since ED doesn't seem to support this—might be a nice lacuna for EDMF to fill.

[1]: http://jsonapi.org/format/#document-resource-object-attributes

**Comment by slindberg** [comment]
@jackweinbender Yes, this project is intended to be 100% compatible with `DS.JSONAPISerializer`, in exactly the way the spec states. Just put your nested JSON in the `attributes` hash, and declare the correct fragment attributes and you're done. Note however that model fragment serializers _themselves_ cannot extend `DS.JSONAPISerializer`, since their raw response is not a full JSON API document (it is simply the specified attribute's raw value).

**Comment by dfreeman** [comment]
@slindberg Totally makes sense. Do you have any thoughts on an ergonomic way to handle that distinction?
If I have an app where the full-fledged models are all powered by JSON API, it seems reasonable to make my application serializer extend `DS.JSONAPISerializer`, but then I need to introduce a bespoke serializer for each fragment in my app. Conversely, if I make the app serializer something else, I need a bespoke `JSONAPISerializer` subclass for each model.
Any thoughts on allowing for a default fragment serializer other than the application one?

**Comment by slindberg** [comment]
@dfreeman Hm, you're right this is a problem. No one wants to create a `export default DS.JSONSerializer.extend();` serializer for every fragment. Opened #135

**Comment by elwayman02** [comment]
@slindberg what's the status of the 2.0-compat version?
